### PR TITLE
Add multi-schema support to omero-marshal

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/rYdxg3fZ/74-multi-schemas-support-omero-marshal

### Rationale and limitations

As discussed as part of the Web API discussion, we need to have support for multiple OMERO/schema versions  in `omero-marshal`. The current PR is based on the latest released OMERO 5.3 milestone should exercise the logic required to support multiple versions.

### Summary of the changes

- add a `get_schema_version()` utility function in the top-level `__init__.py` allowing to map the model version from the OMERO version
- use `distutils.version.StrictVersion` to define the supported OMERO versions
- define a top-level `SCHEMA_VERSION` constant for the currently used schema that can be used to choose the encoders/decoders at runtime
- implement multi-schema support for all encoders/decoders as follows:
   - define `{Element}{YYYMM}{Encoder,Decoder}` classes where `YYYYMM` is the schema year/month and recent model classes inherit from older model classes
   - override the `TYPE` in the 201606 classes
   - for all breaking changes, refactor encoding/decoding using methods and override them in the 2016 classes 
   -  use `SCHEMA_VERSION` to choose the correct set of encoder/decoders and define a generic `{Element}{Encoder,Decoder} ` alias
- update all encoder/decoder unit tests to account for the various schema URLs variations
- add OMERO 5.3. to the list of Travis matrix builds

/cc @will-moore @chris-allan @jburel @knabar

### CODE REVIEW

File: omero_marshal/__init__.py [hunk 1]
```diff
@@ -43,6 +45,22 @@ def get_decoder(t):
         return None
 
 
+def get_schema_version(version):
+    p = re.compile('^(\d+\.\d+\.\d+).*')
+    m = p.match(version)
+    if m is None:
+        raise Exception("Invalid OMERO version number")
```
Comment (will-moore) [inline omero_marshal/__init__.py]: Maybe helpful to have the version number included in the Exception message.

**Comment by will-moore** [comment]
I can't see anywhere that you're using a different ```@type``` with each different schema. Seems it's still hard-coded. E.g.  ```TYPE = 'http://www.openmicroscopy.org/Schemas/ROI/2015-01#Point'```

**Comment by will-moore** [comment]
Presumably every object ```@type``` should be from the same schema E.g. ```http://www.openmicroscopy.org/Schemas/OME/2016-06#Dataset``` and ```http://www.openmicroscopy.org/Schemas/ROI/2016-06#Point``` even if the Dataset encoder/schema is using the 2015-01 encoder?

**Comment by sbesson** [comment]
@will-moore: the type work hasn't been done yet as I was primarily working on the multi-schema infrastructure using subclasses (rather than schema packages). The plan is to definitely to have different `@type` field matching the used schema/OMERO version.

**Comment by chris-allan** [comment]
Now conflicts due to the merging of #8.

File: omero_marshal/__init__.py [hunk 2]
```diff
@@ -43,6 +45,22 @@ def get_decoder(t):
         return None
 
 
+def get_schema_version(version):
+    p = re.compile('^(\d+\.\d+\.\d+).*')
```
Comment (chris-allan) [inline omero_marshal/__init__.py]: Trailing `.*` not required.

Also, I find that having regexes available as package variables so that they can be tested explicitly very helpful. You are already testing the bounds and errors conditions of the regex via your `get_schema_version()` test cases but it can be useful to do regex testing in isolation. Especially when you inevitably have to go back months or years later and remember what you were building the regex to match.

File: omero_marshal/__init__.py [hunk 3]
```diff
@@ -43,6 +45,22 @@ def get_decoder(t):
...
+    m = p.match(version)
+    if m is None:
+        raise Exception("Invalid OMERO version number")
+    v = StrictVersion(m.group(1))
+    if (v >= '5.1' and v < '5.3'):
```
Comment (chris-allan) [inline omero_marshal/__init__.py]: Pedantic, but it might be useful to explicitly say `5.1.0` and `5.3.0` here and in the `elif` below.

**Comment by chris-allan** [comment]
Using `PointEncoder` as an example, while the inheritance tree of `PointEncoder --> Point201501Encoder` and `PointEncoder --> Point201606Encoder` works I would prefer `Point201501Encoder --> Point201606Encoder`.

This allows you to re-use the 2015-01 schema logic where appropriate and override it where necessary. You might go as far as to keep `encode()` the same, implement `get_x()` and `get_y()` methods and then override them. It also ensures that the `TYPE` is explicit on both `Point201501Encoder` and `Point201606Encoder`.

If in the end you need `PointEncoder` for use in the object model or for convenience just assign it:

```
...
if SCHEMA_VERSION == '2015-01':
    encoder = (PointI, Point201501Encoder)
elif SCHEMA_VERSION == '2016-06':
    encoder = (PointI, Point201606Encoder)
PointEncoder = encoder[1]
...
```

File: omero_marshal/decode/decoders/ellipse.py [hunk 4]
```diff
@@ -12,6 +12,7 @@
 from .shape import ShapeDecoder
 from omero.model import EllipseI
 from omero.rtypes import RDoubleI
+from omero_marshal import SCHEMA_VERSION
```
Comment (chris-allan) [inline omero_marshal/decode/decoders/ellipse.py]: This and similar imports should be performed in a relative manner: ```from ... import SCHEMA_VERSION```

File: omero_marshal/__init__.py (hunk 3 above)
Comment (joshmoore) [inline omero_marshal/__init__.py]: Can I throw in "use tuples of integers"?

Comment (chris-allan) [inline omero_marshal/__init__.py]: Would also work. Semver string forms are certainly well supported by `StrictVersion()` though.

**Comment by sbesson** [comment]
Last commit implement the @chris-allan's suggestion in https://github.com/openmicroscopy/omero-marshal/pull/12#issuecomment-226263516 for the `Shape`, `Ellipse` and `Point` encoders/decoders subclassing strategy.

File: omero_marshal/__init__.py (hunk 3 above)
Comment (joshmoore) [inline omero_marshal/__init__.py]: Nice. (Tested locally.)

**Comment by sbesson** [comment]
One question that might be outside the scope of this PR concerns to the expected behavior with regard to future versions. I can see 2 behaviors:
- either be stringent and only register known major.minor OMERO versions. In that PR, this would mean  throw if OMERO version is > 5.3.
- or be more lenient and refine the OMERO/schema version mapping in future versions

The first scenario likely forces us into releasing `omero-marshal` for every new minor OMERO release (for no model change, this can be a simple patch releases of `omero-marshal`) but would ensure deployments have bumped `omero-marshal` to the minimum supported version for a particular OMERO.

**Comment by jburel** [comment]
I think the suggestion https://github.com/openmicroscopy/omero-marshal/pull/12#issuecomment-226263516  makes sense. This will "match" the upgrade stylesheet approach.

**Comment by will-moore** [comment]
Changes look good to me. Tested by using omero_marshal in webgateway shapeMarshal.
Shapes are using  the 2016-06 types where necessary and 2015-01 elsewhere and for other objects. Is the plan to have all objects use the same schema (in another PR?).
I think @chris-allan will have to comment on fixes for his suggestions.

**Comment by sbesson** [comment]
@will-moore: thanks for the review. Yes once these changes are signed off, I plan to apply them to the rest of the objects encoded/decoded by `omero-marshal` (which should have no breaking change apart from the `TYPE` field).

**Comment by chris-allan** [comment]
I'm pretty cool with the class layout, the only other thought I have is maybe to dispense with the static methods. I don't think there's anything wrong with, using `Ellipse` as an example, `set_x(self, obj, value)` or even `set_x(ellipse, value)` if you want to be more declarative. You're calling the methods as if they were instance methods anyway.

**Comment by sbesson** [comment]
@chris-allan: last commit should drop the static decorators.

**Comment by chris-allan** [comment]
Looking good to me.

**Comment by sbesson** [comment]
While this PR is meant to be fully backwards-compatible, in terms of versioning, thoughts about tagging/documenting the additions made by @knabar as `0.3.1` and have this PR starting a new development cycle for `0.4.0` which will include full support for both the 2016-06 and 2015-01 models?

**Comment by chris-allan** [comment]
Starting with this PR as the basis for `0.4.0` sounds good to me, @sbesson. We can probably tag and release `0.3.1` in the coming days.

**Comment by sbesson** [comment]
Following the release of `0.3.1`, the last set of commits should update all encoders/decoders to use the multi-schema strategy and update the README to indicate 5.3.x support. The PR description has been updated to reflect the latest changes.

As discussed with @chris-allan, the current handling of transforms introduced in https://github.com/openmicroscopy/omero-marshal/pull/8 will need refactoring since this element will be modeled as a proper object from OMERO 5.3.0 (see https://github.com/openmicroscopy/openmicroscopy/pull/4672 for more context). Once we have a milestone release of OMERO 5.3 with these objects, we might want to derive a set of transform encoders/decoders and fallback to the string handling strategy only for older OMERO versions /cc @mtbc @jburel

**Comment by will-moore** [comment]
Looking at your last comment @sbesson I guess this is expected for an Ellipse with transform?
```
  File "/Users/wmoore/Desktop/OMERO-MARSHAL/omero-marshal/omero_marshal/encode/encoders/ellipse.py", line 22, in encode
    v = super(Ellipse201501Encoder, self).encode(obj)
  File "/Users/wmoore/Desktop/OMERO-MARSHAL/omero-marshal/omero_marshal/encode/encoders/shape.py", line 39, in encode
    v, 'Transform', self.encode_transform(obj.transform))
  File "/Users/wmoore/Desktop/OMERO-MARSHAL/omero-marshal/omero_marshal/encode/encoders/shape.py", line 59, in encode_transform
    tr, args = transform[:-1].split('(')
TypeError: 'AffineTransformI' object has no attribute '__getitem__'
")
```

**Comment by sbesson** [comment]
@will-moore which build are you using? If this is a merge build post 5.2.0-m2 with @mtbc's DB change included, yes this is typically the error I would expect.

**Comment by will-moore** [comment]
@sbesson Yes, I'm using latest OMERO DB and head of this branch.
I'm looking to read shapes from OMERO to OMERO.figure, so I need to convert Insight's AffineTransform into simple rotation (and translation?) E.g.
```
{"type":"Ellipse","cx":247,"cy":246,"rx":167,"ry":83,"rotation":51}
```
Any ideas how to go about that?

**Comment by mtbc** [comment]
What if it has skew/shear? Anyhow, the comments on https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/model/resources/mappings/roi.ome.xml#L134 should be helpful.

**Comment by will-moore** [comment]
Ah, I just found http://blog.openmicroscopy.org/data-model/future-plans/2016/06/20/shape-transforms/ while trawling twitter! Still, doesn't help me get rotation and translation from a matrix.

**Comment by sbesson** [comment]
Should we handle the transformation discussion in a separate PR/issue as this is outside the scope of this particular PR?

I think translation can be directly read from two of the components of the `AffineTransform` while rotation needs to be computed from the other components. Which library are you using to render transforms and is there one that would support these affine transforms natively?

**Comment by mtbc** [comment]
It does get a bit hairy in the general case, e.g., when the rotation is not around (0, 0). Third-party library support would be very helpful if available.

**Comment by chris-allan** [comment]
Getting a simple rotation or translation from the `AffineTransform` can be done by extracting the correct values from the matrix. There are very good explanations on how to do this in the forward direction (`rotate()` or `translate()` --> `matrix()`) on #8 and by extension openmicroscopy/design#33. However, this can be quite tricky as the SVG string encoding of these transformations is in degrees and an affine transform works in radians. I would not do this without an extensive set of tests. During the process of writing #8 we found a number of examples online that were just plain incorrect. 

Furthermore, as @mtbc has already outlined there may be further transformations such as skew, etc. applied which `rotate()` and/or `translate()` would not be able to take into account.

I would strongly suggest utilizing a transformation matrix and not relying on rotation or translation exclusively. There is complete support for this in browser with SVG via the transform attribute and `omero_marshal` itself is already doing the hard work of uniformly standardizing on `matrix()` for you.

**Comment by will-moore** [comment]
Moved discussion to https://trello.com/c/zGuNePnu/109-load-rois-from-omero

**Comment by chris-allan** [comment]
Refactoring of OMERO rtype translation from #17 now merged. This PR will need to have merge conflicts resolved.

**Comment by sbesson** [comment]
Pushed merge commits with conflict resolution. Following brief discussion with @chris-allan, I also took advantage of the refactoring in #17 to use class variables rather than method overloading in `Ellipse/Point` encoders/decoders to account for the property name variation between schemas/versions.

**Comment by sbesson** [comment]
Closing/reopening to re-run Travis with the latest tag

**Comment by sbesson** [comment]
73ce60c should add minimal support for the `AffineTransformI` objects introduce in 5.3.0-m3 in `omero-marshal`. An interesting 5.3+ only use case that is not currently covered by the current implementation/testing is the sparse case i.e. an `AffineTransform` with one or multiple `null` values but not all of them.
In that case, there are two policies we could adopt for the tranform encoding:
1. create a sparse transform dictionary. Advantage: the round-trip would preserve the exact original transform
2. create a complete transform dictionary and fill using the default valuse (0 or 1 depending on the transform position). Advantage: clear marshalling and unification with the schema.
 
To be discussed tomorrow at the Web API meeting.

**Comment by sbesson** [comment]
Re https://github.com/openmicroscopy/omero-marshal/pull/12#issuecomment-243212583, discussed with @mtbc who pointed out that  the `AffineTransform` attributes are not null in the DB so we might not need to consider the case above at all as `shape.transform` will either be `null` or a transform with all the `a??` attributes filled.

**Comment by sbesson** [comment]
As a general RFE on transforms, I wonder if there is a case for refactoring it like ROI/Shape in the future, i.e. migrate the transform encoding/decoding to `encode/encoder/transform.py`  and `decode/decoder/transform.py` and delegate to these classes in the shape encoding/decoding step. /cc @knabar @chris-allan

**Comment by will-moore** [comment]
I have started to use this PR in
https://github.com/openmicroscopy/openmicroscopy/pull/4708/commits/eb8eaa7d7c61d8f98e663978fe80102688ec0152

E.g. OME_SCHEMA_URL is provided in http://10.0.51.145/web/webgateway/api/v1.0/
Tests using this are passing: https://10.0.51.145:8443/job/OMERO-test-integration/6/

Using omero_marshal in webgateway marshal.py shapeMarshal() provides seemingly valid output when compared to current json output, using develop OMERO branch.
Will try against older server...

**Comment by will-moore** [comment]
Fails with OMERO 5.0.8 (as expected?) with
```
File "/Users/wmoore/Desktop/OMERO-MARSHAL/omero-marshal/omero_marshal/encode/__init__.py" in <module>
  13. from omero_model_UnitBase import UnitBase
Exception Type: ImportError at /webclient/
Exception Value: No module named omero_model_UnitBase
```

**Comment by will-moore** [comment]
With OMERO 5.2.5 I'm seeing this Ellipse:
```
...
RadiusX: 60,
Y: 259,
X: 174,
StrokeColor: -993737532,
TheT: 0,
@id: 3,
@type: "http://www.openmicroscopy.org/Schemas/ROI/2015-01#Ellipse",
TheZ: 22
```
The schema correctly says 2015 but I'm seeing attributes of OMERO5.3.
Looking at the code, I can see that this is the expected behaviour, but I somehow expected the API of omero_mashal to reflect the underlying OMERO version.

**Comment by sbesson** [comment]
@will-moore: yes the minimal requirement for omero-marshal is 5.1. Re attributes, I suppose you refer to `RadiusX`? As indicated by the `@type` URL, the reference for the field naming convention when marshalling has been to use the OME Data Model.

**Comment by will-moore** [comment]
@sbesson Understood. Looking good to merge as far as my testing is concerned.

**Comment by chris-allan** [comment]
Good to merge from my perspective.
