### PR TITLE
Initial support for Event

### PR DESCRIPTION
**Pull request by chris-allan**
.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#3](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/3/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/3/consoleText) for more details.
Possible conflicts:
  - PR #29 chris-allan 'Initial support for FileAnnotation and OriginalFile'
    - tests/unit/conftest.py
  - PR #33 chris-allan 'Encode/Decode Experimenters with ExperimenterGroup'
    - tests/unit/conftest.py
    - tests/unit/test_base_decoder.py
  - Upstream changes
    - tests/unit/conftest.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#4](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/4/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/4/consoleText) for more details.
Possible conflicts:
  - PR #29 chris-allan 'Initial support for FileAnnotation and OriginalFile'
    - tests/unit/conftest.py
  - PR #33 chris-allan 'Encode/Decode Experimenters with ExperimenterGroup'
    - tests/unit/conftest.py
    - tests/unit/test_base_decoder.py
  - Upstream changes
    - tests/unit/conftest.py

--conflicts

**Comment by will-moore** [comment]
https://py3-ci.openmicroscopy.org/web/api/v0/m/projects/ is currently giving:

```
\"/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/omero_marshal/encode/encoders/project.py\", line 22, in encode
    v = super(Project201501Encoder, self).encode(obj)
  File \"/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/omero_marshal/encode/encoders/annotation.py\", line 67, in encode
    v = super(Annotatable201501Encoder, self).encode(obj)
  File \"/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/omero_marshal/encode/__init__.py\", line 53, in encode
    v['omero:details'] = encoder.encode(obj.details)
  File \"/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/omero_marshal/encode/encoders/details.py\", line 36, in encode
    v['creationEvent'] = encoder.encode(obj.creationEvent)
  File \"/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/omero_marshal/encode/encoders/event.py\", line 32, in encode
    v['type'] = encoder.encode(obj.type)
  File \"/home/omero/workspace/OMERO-web/omero-virtualenv/lib/python3.6/site-packages/omero_marshal/encode/encoders/enum.py\", line 22, in encode
    self.set_if_not_none(v, 'value', obj.value)
  File \"/home/omero/workspace/OMERO-web/OMERO.web/lib/python/omero_model_EventTypeI.py\", line 175, in __getattr__
    raise AttributeError(\"'%s' object has no attribute '%s' or '%s'\" % (self.__class__.__name__, getter, questn))
AttributeError: 'EventTypeI' object has no attribute 'getValue' or 'isValue'
```

**Comment by will-moore** [comment]
Until yesterday, this PR was excluded due to conflicts with #29.
But now that PR is excluded, this one is merged and causing errors, E.g. failure of https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-training/110/ (JSON api).

Need to exclude this PR too:

--exclude

**Comment by will-moore** [comment]
This PR has been excluded because of conflicts with #29. But that was excluded 2 days ago so this PR is being merged and is causing failures of
https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-training/110/ (JSON api).

Need to exclude this too:

--exclude
